INSERT INTO STOCK (id, name, CURRENT_PRICE, last_Update ) VALUES ('1','stock1', '565656589', CURRENT_TIMESTAMP);
INSERT INTO STOCK (id, name, CURRENT_PRICE, last_Update ) VALUES ('2','stock2', '565656588', CURRENT_TIMESTAMP);
INSERT INTO STOCK (id, name, CURRENT_PRICE, last_Update ) VALUES ('3','stock3', '565656587', CURRENT_TIMESTAMP);